import { DRAGON_MAX_HP, DRAGON_ARMOR } from "./constants";
import type { PredatorKind, BossKind } from "./types";

export const PREDATOR_STATS: Record<PredatorKind, { hp: number; attackDamage: number; aggroRange: number; strikeRange: number; speed: number; cooldown: number }> = {
  spider: { hp: 25, attackDamage: 3, aggroRange: 8, strikeRange: 1.7, speed: 2.2, cooldown: 1.45 },
  wolf: { hp: 65, attackDamage: 6, aggroRange: 13, strikeRange: 2.05, speed: 3.05, cooldown: 1.35 },
  lion: { hp: 78, attackDamage: 7, aggroRange: 15, strikeRange: 2.35, speed: 3.3, cooldown: 1.15 },
};

export const BOSS_STATS: Record<
  BossKind,
  { name: string; maxHp: number; armor: number; fireDamage: number; clawDamage: number; attackRange: number; collisionRadius: number; collisionHeight: number; scale: number; body: number; belly: number; wing: number; glow: number }
> = {
  dragon: {
    name: "용",
    maxHp: DRAGON_MAX_HP,
    armor: DRAGON_ARMOR,
    fireDamage: 8,
    clawDamage: 9,
    attackRange: 28,
    collisionRadius: 4.2,
    collisionHeight: 5.4,
    scale: 1.08,
    body: 0x8f1d2c,
    belly: 0xf59e0b,
    wing: 0xef4444,
    glow: 0xff4a1f,
  },
  fire_dragon: {
    name: "파이어 드래곤",
    maxHp: 700,
    armor: 62,
    fireDamage: 14,
    clawDamage: 13,
    attackRange: 31,
    collisionRadius: 4.8,
    collisionHeight: 6.1,
    scale: 1.22,
    body: 0xc2410c,
    belly: 0xffd166,
    wing: 0xff6b1a,
    glow: 0xff7a1a,
  },
  red_dragon: {
    name: "레드 드래곤",
    maxHp: 900,
    armor: 78,
    fireDamage: 18,
    clawDamage: 16,
    attackRange: 34,
    collisionRadius: 5.1,
    collisionHeight: 6.5,
    scale: 1.32,
    body: 0x991b1b,
    belly: 0xf97316,
    wing: 0xdc2626,
    glow: 0xff2d2d,
  },
  laser_dragon: {
    name: "레이저 드래곤",
    maxHp: 1150,
    armor: 95,
    fireDamage: 25,
    clawDamage: 19,
    attackRange: 42,
    collisionRadius: 5.4,
    collisionHeight: 6.8,
    scale: 1.4,
    body: 0x155e75,
    belly: 0x67e8f9,
    wing: 0x22d3ee,
    glow: 0x4adeff,
  },
  dark_dragon: {
    name: "다크 드래곤",
    maxHp: 1450,
    armor: 115,
    fireDamage: 34,
    clawDamage: 26,
    attackRange: 45,
    collisionRadius: 5.8,
    collisionHeight: 7.2,
    scale: 1.5,
    body: 0x1f1235,
    belly: 0x6d28d9,
    wing: 0x4c1d95,
    glow: 0xa855f7,
  },
  immortal: {
    name: "불멸의 존재",
    maxHp: 2200,
    armor: 145,
    fireDamage: 46,
    clawDamage: 38,
    attackRange: 50,
    collisionRadius: 6.2,
    collisionHeight: 7.8,
    scale: 1.62,
    body: 0x111827,
    belly: 0x9ca3af,
    wing: 0x0f172a,
    glow: 0xf8fafc,
  },
};
