[/Script/EngineSettings.GameMapsSettings]
; 코드-퍼스트 [MUST] — .umap 에셋 저작 없이 엔진 내장 Entry 맵으로 부팅 (ue5-client-design §3)
GameDefaultMap=/Engine/Maps/Entry.Entry
EditorStartupMap=/Engine/Maps/Entry.Entry
GlobalDefaultGameMode=/Script/WorldConquestUE.WCGameMode

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=2852823D480835670BCE798E4B7743F9
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

